services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  telegram-bot:
    build: .
    restart: always
    env_file:
      - .env

volumes:
  db_data:
